use_frameworks!

target 'ZSpinner_Example' do
  pod 'ZSpinner', :path => '../'

  target 'ZSpinner_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
