use_frameworks!

target 'ZSpinner_Example' do
  pod 'ZSpinner', :path => '../'

  target 'ZSpinner_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
